## TENSORS

### 0-d Tensors (Scaler)

In [1]:
import numpy as np

In [2]:
a= np.array(2)

In [3]:
a

array(2)

In [4]:
a.ndim

0

### 1-d Tensors (Vector)

In [5]:
a= np.array([1,2])

In [6]:
a

array([1, 2])

In [7]:
a.ndim

1

### 2-d Tensors (Matrices)

In [8]:
a= np.array([[1,2],[2,4]])

In [9]:
a

array([[1, 2],
       [2, 4]])

In [10]:
a.ndim

2

### 3-d Tansors (N-D Tensers)

In [11]:
a= np.array([[[1,2],[2,4]],
             [[5,6],[7,8]]])

In [12]:
a

array([[[1, 2],
        [2, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
a.ndim

3

### 4-d Tensors

In [14]:
a= np.array([[[[1,2],[3,4]]],[[[5,6],[7,8]]],[[[9,10],[11,12]]],[[[13,14],[15,16]]]])

In [15]:
a

array([[[[ 1,  2],
         [ 3,  4]]],


       [[[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]]]])

In [16]:
a.ndim

4

### 5-d Tensors

In [17]:
a= np.array([[[[[1,2],[3,4]]]],[[[[5,6],[7,8]]]],[[[[9,10],[11,12]]]],[[[[13,14],[15,16]]]],[[[[17,18],[19,20]]]],[[[[21,22],[23,24]]]]])

In [18]:
a

array([[[[[ 1,  2],
          [ 3,  4]]]],



       [[[[ 5,  6],
          [ 7,  8]]]],



       [[[[ 9, 10],
          [11, 12]]]],



       [[[[13, 14],
          [15, 16]]]],



       [[[[17, 18],
          [19, 20]]]],



       [[[[21, 22],
          [23, 24]]]]])

In [19]:
a.ndim

5

### 6-d Tensors

In [20]:
a=np.array([[[[[[1,2],[3,4]]]]]])

In [21]:
a

array([[[[[[1, 2],
           [3, 4]]]]]])

In [22]:
a.ndim

6

## Diagram to understad

![](tenserdiagram.jpeg)